name: test-basic-artifact
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Upload dummy artifact
        uses: actions/upload-artifact@v2
        with:
          name: dummy
          path: README.md